services:
  postgres:
    image: postgres:16
    container_name: banco_horadoqa_postgres
    restart: always
    ports:
      - "5432:5432"   # 5433 no host, 5432 no container
    environment:
      POSTGRES_DB: banco_horadoqa
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      TZ: America/Sao_Paulo
    volumes:
      - banco_horadoqa_postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  backend:
    build: .
    container_name: api_candidatos
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: banco_horadoqa
      DB_PORT: 5432
    depends_on:
      - postgres

volumes:
  banco_horadoqa_postgres_data:
